networks:
  benchnet:
    driver: bridge

services:
  runnerDDS1:
    image: psmark-runner:latest
    container_name: runnerDDS1
    hostname: runnerDDS1
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS1.benchnet
    environment:
      DIST_MODE: name
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner1
      NODE_HOST_OVERRIDE: ${NODE5_HOST_OVERRIDE:-}
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_dds
    volumes:
      - ./out/runnerDDS1:/app/out
      - ./out/opendds:/app/logs
      - ./results:/app/results

  runnerDDS2:
    image: psmark-runner:latest
    container_name: runnerDDS2
    hostname: runnerDDS2
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS2.benchnet
    environment:
      DIST_MODE: name     
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner2
      NODE_HOST_OVERRIDE: ${NODE5_HOST_OVERRIDE:-}
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_dds
    volumes:
      - ./out/runnerDDS2:/app/out
      - ./out/opendds:/app/logs
      - ./results:/app/results

  runnerDDS3:
    image: psmark-runner:latest
    container_name: runnerDDS3
    hostname: runnerDDS3
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS3.benchnet
    environment:
      DIST_MODE: name
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner3
      NODE_HOST_OVERRIDE: ${NODE5_HOST_OVERRIDE:-}
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_dds
    volumes:
      - ./out/runnerDDS3:/app/out
      - ./out/opendds:/app/logs
      - ./results:/app/results

  runnerDDS4:
    image: psmark-runner:latest
    container_name: runnerDDS4
    hostname: runnerDDS4
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS4.benchnet
    environment:
      DIST_MODE: name
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner4
      NODE_HOST_OVERRIDE: ${NODE5_HOST_OVERRIDE:-}
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_dds
    volumes:
      - ./out/runnerDDS4:/app/out
      - ./out/opendds:/app/logs
      - ./results:/app/results

  runnerDDS5:
    image: psmark-runner:latest
    container_name: runnerDDS5
    hostname: runnerDDS5
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS5.benchnet
    environment:
      DIST_MODE: name
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner5
      NODE_HOST_OVERRIDE: ${NODE5_HOST_OVERRIDE:-}
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_dds
    volumes:
      - ./out/runnerDDS5:/app/out
      - ./out/opendds:/app/logs
      - ./results:/app/results