networks:
  benchnet:
    driver: bridge

services:
  nanomq:
    build:
      context: .
      dockerfile: Dockerfile.nanomq
    image: nanomq-with-exporter
    container_name: nanomq
    hostname: nanomq
    domainname: benchnet
    environment:
      NANOMQ_LOG_TO: file
      NANOMQ_LOG_LEVEL: info
      NANOMQ_LOG_DIR: "/logs"
    volumes:
      - ./out/nanomq:/logs
    networks:
      benchnet:
        aliases: ["nanomq", "mqtt", "broker"]
    ports: ["1883:1883"]
    healthcheck:
      test: ["CMD-SHELL","nc -z 127.0.0.1 1883"]
      interval: 15s
      timeout: 1s
      retries: 20
      start_period: 2s

  runnerMQTT1:
    image: psmark-runner:latest
    container_name: runnerMQTT1
    hostname: runnerMQTT1
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerMQTT1.benchnet   
    environment:
      DIST_MODE: name 
      NODE_BASE: runner1
      NODE_HOST_OVERRIDE: ${NODE1_HOST_OVERRIDE:-}
      BROKER_HOST: nanomq
      BROKER_PORT: 1883
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-mqtt_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_mqttv5
    volumes:
      - ./out/runnerMQTT1:/app/out
      - ./results:/app/results
    depends_on:
      nanomq:
        condition: service_healthy

  runnerMQTT2:
    image: psmark-runner:latest
    container_name: runnerMQTT2
    hostname: runnerMQTT2
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerMQTT2.benchnet   
    environment:
      DIST_MODE: name 
      NODE_BASE: runner2
      NODE_HOST_OVERRIDE: ${NODE2_HOST_OVERRIDE:-}
      BROKER_HOST: nanomq
      BROKER_PORT: 1883
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-mqtt_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_mqttv5
    volumes:
      - ./out/runnerMQTT2:/app/out
      - ./results:/app/results
    depends_on:
      nanomq:
        condition: service_healthy

  runnerMQTT3:
    image: psmark-runner:latest
    container_name: runnerMQTT3
    hostname: runnerMQTT3
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerMQTT3.benchnet
    environment:
      DIST_MODE: name 
      NODE_BASE: runner3
      NODE_HOST_OVERRIDE: ${NODE3_HOST_OVERRIDE:-}
      BROKER_HOST: nanomq
      BROKER_PORT: 1883
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-mqtt_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_mqttv5
    volumes:
      - ./out/runnerMQTT3:/app/out
      - ./results:/app/results
    depends_on:
      nanomq:
        condition: service_healthy

  runnerMQTT4:
    image: psmark-runner:latest
    container_name: runnerMQTT4
    hostname: runnerMQTT4
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerMQTT4.benchnet
    environment:
      DIST_MODE: name 
      NODE_BASE: runner4
      NODE_HOST_OVERRIDE: ${NODE4_HOST_OVERRIDE:-}
      BROKER_HOST: nanomq
      BROKER_PORT: 1883
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-mqtt_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_mqttv5
    volumes:
      - ./out/runnerMQTT4:/app/out
      - ./results:/app/results
    depends_on:
      nanomq:
        condition: service_healthy

  runnerMQTT5:
    image: psmark-runner:latest
    container_name: runnerMQTT5
    hostname: runnerMQTT5
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerMQTT5.benchnet
    environment:
      DIST_MODE: name 
      NODE_BASE: runner5
      NODE_HOST_OVERRIDE: ${NODE5_HOST_OVERRIDE:-}
      BROKER_HOST: nanomq
      BROKER_PORT: 1883
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-mqtt_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: scalabilitysuite_smart_home_mqttv5
    volumes:
      - ./out/runnerMQTT5:/app/out
      - ./results:/app/results
    depends_on:
      nanomq:
        condition: service_healthy
